// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TH_502045_1.Models;

#nullable disable

namespace TH_502045_1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TH_502045_1.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RouteId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            DestinationName = "Ga Bến Thành",
                            IsActive = true,
                            Price = 15000m
                        },
                        new
                        {
                            RouteId = 2,
                            DestinationName = "Ga Nhà hát Thành phố",
                            IsActive = true,
                            Price = 15000m
                        },
                        new
                        {
                            RouteId = 3,
                            DestinationName = "Ga Ba Son",
                            IsActive = true,
                            Price = 15000m
                        },
                        new
                        {
                            RouteId = 4,
                            DestinationName = "Ga Tân Cảng",
                            IsActive = true,
                            Price = 20000m
                        },
                        new
                        {
                            RouteId = 5,
                            DestinationName = "Ga Suối Tiên",
                            IsActive = true,
                            Price = 25000m
                        });
                });

            modelBuilder.Entity("TH_502045_1.Models.TicketOrder", b =>
                {
                    b.Property<int>("TicketOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketOrderId"));

                    b.Property<string>("BarcodeData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short?>("isTransferred")
                        .HasColumnType("smallint");

                    b.HasKey("TicketOrderId");

                    b.HasIndex("RouteId");

                    b.ToTable("TicketOrders");
                });

            modelBuilder.Entity("TH_502045_1.Models.TicketOrder", b =>
                {
                    b.HasOne("TH_502045_1.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId");

                    b.Navigation("Route");
                });
#pragma warning restore 612, 618
        }
    }
}
